## Apilando

Muchos Array pueden ser apilados juntos en diferentes ejes.

In [1]:
import numpy as np
rg = np.random.default_rng(1)

a = np.floor(10*rg.random((2, 2)))
a

array([[5., 9.],
       [1., 9.]])

In [2]:
b = np.floor(10*rg.random((2, 2)))
b

array([[3., 4.],
       [8., 4.]])

In [3]:
np.vstack((a ,b))

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.]])

In [4]:
np.hstack((a, b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

La función **columna_stack** apila Arrays de una dimensión como columnas de un arreglo de dos dimensiones. 
Esto es equivalente a la función **hstack** únicamente para los Arrays bidimensionales

In [5]:
from numpy import newaxis

np.column_stack((a, b)) # con arrays de dos dimensiones

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [6]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b)) # retorna un array bidimensional

array([[4., 3.],
       [2., 8.]])

In [7]:
np.hstack((a, b)) # el resultado es diferente

array([4., 2., 3., 8.])

In [ ]:
a[:, newaxis] # a como vector bidimensional

In [8]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [9]:
np.hstack((a[:, newaxis], b[:, newaxis])) # el resultado es el mismo

array([[4., 3.],
       [2., 8.]])

La función **row_stack** es equivalente a vstack para cualquier Array de entrada. De hecho, row_stack es un alias para 
vstack.

In [10]:
np.column_stack is np.hstack

False

In [11]:
np.row_stack is np.vstack

True