## Dividiendo un arreglo en otros más pequeños


Utilizando **hsplit** puedes dividir un Array a lo largo de su eje horizontal, se tiene que especificar el numero de 
Arrays equivalentes en forma a retornar o especificando las columnas en las cuales la división debe de ocurrir.

In [1]:
import numpy as np
rg = np.random.default_rng(1)

a = np.floor(10*rg.random((2,12)))
a

array([[5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.]])

In [2]:
# dividiendo a en tres partes

np.hsplit(a, 3)

[array([[5., 9., 1., 9.],
        [3., 7., 3., 4.]]),
 array([[3., 4., 8., 4.],
        [1., 4., 2., 2.]]),
 array([[5., 0., 7., 5.],
        [7., 2., 4., 9.]])]

In [3]:
# dividiendo a despues de la tercera y cuarta columna

np.hsplit(a, (3, 4))

[array([[5., 9., 1.],
        [3., 7., 3.]]),
 array([[9.],
        [4.]]),
 array([[3., 4., 8., 4., 5., 0., 7., 5.],
        [1., 4., 2., 2., 7., 2., 4., 9.]])]