## Funciones universales
Numpy provee de funciones que resultaran muy familiares a las matemáticas como por ejemplo la función **sin**, **cos**, 
**exp**. En Numpy, a estas funciones se les llama funciones universales. En Numpy estas funciones operan en 
cada elemento del Array, produciendo un Array como salida.

In [1]:
import numpy as np

In [2]:
B = np.arange(3)
B

array([0, 1, 2])

In [3]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [4]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [5]:
C = np.array([2., -1., 4.])
C

array([ 2., -1.,  4.])

In [6]:
np.add(B, C)

array([2., 0., 6.])