## Impriemiendo Arrays

Cuando imprimes un Array, Numpy lo despliega de una manera similar a una lista, solo que con el siguiente esquema:

El ultimo eje se imprime de izquierda a derecha.

El penúltimo es impreso de arriba hacia abajo.

El resto también son impresos de arriba hacia abajo, con cada parte separada por una línea en blanco.

Los Arrays unidimensionales son impresos como filas, los bidimensionales son impresos como matrices. 
Y los tridimensionales son impresos como una lista de matrices.

In [3]:
import numpy as np

In [4]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Si un arreglo es demasiado largo como para ser imprimido, Numpy automáticamente omite la parte central del Array e 
imprime únicamente las orillas. 

In [8]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [9]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


Para deshabilitar la opción anterior y forzar a Numpy a imprimir el Array completo, puedes cambiar la opción se 
impresión usando **set_printoptions**.

In [13]:
from numpy import sys 
np.set_printoptions(threshold=sys.maxsize)

In [15]:
print(np.arange(500))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24