 ## Indexación, separación e iteraciones

Los Arrays unidimensionales puedes ser indexados, separados y iterados como se fuera una lista de Python común y 
corriente.

In [2]:
import numpy as np

a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
# indexado

a[2]

8

In [4]:
# separado desde la posición 2 hasta la posición 5

a[2:5]

array([ 8, 27, 64], dtype=int32)

In [5]:
# equivalente a [0:6:2] = 1000
# desde el inicio hasta la posición 6, se cambia cada unos de esos elementos por un mil

a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [7]:
a[::-1] # array al reves

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [8]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


los array multidimensionales pueden tener un índice por eje. Estos indicen son dados en una tupla separada por colas.

In [9]:
def f(x, y):
    return 10 * x + y

In [10]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [11]:
b[2, 3] # cada fila de la segunda columna

23

In [12]:
b[:, 1] # equivalene al ejemplo anterior

array([ 1, 11, 21, 31, 41])

In [13]:
b[1:3, :] # cada columna de la segunda y tercera fila

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

Cuando se proporcionan menos índices que el numero de ejes que contiene el Array, los índices faltantes son considerados 
partes completas.

In [14]:
# equivalente a b[-1, :]
b[-1]

array([40, 41, 42, 43])

Puedes utilizar puntos (.) para representar los índices faltantes para la tupla de índices completa de ese Array

In [17]:
# x[1,2,...] es equivalente a x[1,2,:,:,:]

c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c.shape

(2, 2, 3)

In [18]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [19]:
c[...,2]

array([[  2,  13],
       [102, 113]])

La iteración en Arrays multidimensionales se hace con respecto al primer eje.

In [20]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


Si quieres desplegar todos los elementos de un arreglo puedes usar la propiedad **flat**

In [21]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
