## Manipulación de forma
#### Cambiando la forma de un Array.

Un Array tiene una forma dada por el numero de elementos de cada eje.

In [1]:
import numpy as np
rg = np.random.default_rng(1)

a = np.floor(10*rg.random((3, 4)))
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [2]:
a.shape

(3, 4)

La forma de un arreglo puede ser cambiada con varios comandos. Nótese que los siguientes comandos todos retornan un 
Array modificado, pero no cambia al Array original.

In [3]:
a.ravel() # retorna el array como una lista

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [4]:
a.reshape(6, 2) # retorna el array con una forma modificada

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [5]:
a.T # retorna el array traspuesto

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [6]:
a.T.shape

(4, 3)

In [7]:
a.shape

(3, 4)

La función **reshape** retorna la forma modificada del Array, mientras que el **ndarray.resize** modifica el arreglo 
libre.

In [8]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [10]:
a.resize((2, 6))
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.]])

Si una dimensión es dada como un **-1** en la operación **reshape** la otra dimensión es automáticamente calculada.

In [11]:
a.reshape(3, -1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])