## Operaciones básicas

Las operadoros aritméticos en matrices se aplican en los elementos.

In [1]:
import numpy as np

a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [2]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [3]:
c = a-b
c

array([20, 29, 38, 47])

In [4]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [5]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [6]:
a<35

array([ True,  True, False, False])

A diferencia de otros lenguajes de matrices, el operador del producto * opera en cada elemento del Array Numpy. 
El producto de 2 matrices puede ser obtenido utilizando el operador @ o la función **dot**.

In [7]:
A = np.array([[1,1 ], [0, 1]])
A

array([[1, 1],
       [0, 1]])

In [8]:
B = np.array([[2, 0], [3, 4]])
B

array([[2, 0],
       [3, 4]])

In [9]:
# producto de los elementos pertenecientes a la matriz

A * B

array([[2, 0],
       [0, 4]])

In [10]:
# producto matricial

A @ B

array([[5, 4],
       [3, 4]])

In [11]:
# otra forma de producto matricial

A.dot(B)

array([[5, 4],
       [3, 4]])

Algunas operaciones, como **+=** y ***=** se utiliza para modificar el Array existente y no tener que crear uno nuevo.

In [12]:
rg = np.random.default_rng(1) # crea una instancia del generador de números aleatorios de numpy.
rg

Generator(PCG64) at 0x1E829BB4138

In [16]:
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
a *=  3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [18]:
b += a
b

array([[3.82770259, 3.40919914, 3.54959369],
       [3.02755911, 3.75351311, 3.53814331]])

In [ ]:
a += b # un error común, b no se convierte automáticamente a tipo entero

Cuando estas realizando operaciones con Arrays, el tipo del Array resultante es el más general o el más preciso.

In [19]:
from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [20]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [21]:
c.dtype.name

'float64'

In [22]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

Muchas operaciones de unificación, como el de calcular la suma de todos los elementos de un array están implementadas 
en los métodos de la clase **ndarray** 

In [23]:
a = rg.random((2, 3))
a

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [24]:
a.sum()

2.412007822394087

In [25]:
a.min()

0.13404169724716475

In [26]:
a.max()

0.7884287034284043

Por default, la operación se aplica con todos los elementos del Array como si fuera una lista de números, sin importar 
su forma. Sin embargo, especificando el parámetro **axis** puedes aplicar operaciones a ejes específicos dentro del 
array.

In [27]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
b.sum(axis=0) # suma obtenida de los elementos de cada columna

array([12, 15, 18, 21])

In [31]:
b.min(axis=1) # minimo de cada fila

array([0, 4, 8])

In [32]:
b.cumsum(axis=1) # suma acumulativa de todas las filas

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)